### ISSUE TITLE
MegaMerged Noto Sans and Noto Serif?

### ISSUE THREAD

**Issue by davelab6** [notofonts/noto-docs#35]
Is there a single mega-merged Noto Sans file available publicly, that users can substitute for eg [Arial Unicode MS](https://learn.microsoft.com/en-us/typography/font-list/arial-unicode-ms)?

Use case: Rendering user generated text into PDFs after eSignature. This is possible with mixed language strings, but the PDF AcroForm Text field format only allows a single font to be set per text field (see eg [stackoverflow.com/questions/47995062/pdfbox-api-how-to-change-font-to-handle-cyrillic-values-in-an-acroform-field](https://stackoverflow.com/questions/47995062/pdfbox-api-how-to-change-font-to-handle-cyrillic-values-in-an-acroform-field)), and has no support for a fallback stack.

I guess it would be helpful to have access to both OT1.9.x/[BE](https://github.com/harfbuzz/boring-expansion-spec) versions, with 65k/all characters :)

**Comment by simoncozens** [comment]
There isn't one yet, but we can certainly look at putting one together...

**Comment by davelab6** [comment]
@simoncozens do you think you could make this happen in January, or Q1?

**Comment by simoncozens** [comment]
Yep, nearly there. Currently debugging some issues with merging some fonts which have vhea tables and others which don't. (Related mystery: Find out why some non-vertical fonts like Canadian Aboriginal and Ethiopic have vhea tables. Third-order digression: Write a fontbakery check to WARN if non-vertical scripts have a vhea table.)

**Comment by moyogo** [comment]
@simoncozens some glyphs have vertical metrics. It can happen by mistake.

**Comment by davelab6** [comment]
> @simoncozens some glyphs have vertical metrics. It can happen by mistake.

Could you say more about this? I'm not sure what you mean exactly

**Comment by moyogo** [comment]
>> some glyphs have vertical metrics. It can happen by mistake.
> Could you say more about this? I'm not sure what you mean exactly

The vhea, vmtx, VORG and VVAR tables are created when sources have vertical layout metrics.

Noto Sans Ethiopic and Noto Serif Ethiopic have `vertWidth = 0;` defined for tons of glyphs.
Noto Sans Canadian Aboriginal has `openTypeVheaVertTypoAscender`, `openTypeVheaVertTypoDescender` and `openTypeVheaVertTypoLineGap` defined.

**Comment by anthrotype** [comment]
so you're using fontTools.merge tool to merge the font binaries. I thought you'd try to merge the sources. The binary merge script for Noto already existed as you may know already, at https://github.com/notofonts/nototools/blob/main/nototools/merge_noto.py

**Comment by simoncozens** [comment]
I didn't know of that, to be honest. I always forget about nototools because there is so much in there that is no longer relevant; none of the scripts there are used in the current production process.

There are some good things about that merge script, but also some bad things; it doesn't handle Serif, we don't need stub GSUB tables any more. But more importantly: I'm trying to keep all the data about repos etc. in a [single source of truth](https://github.com/notofonts/notofonts.github.io/blob/main/fontrepos.json) so we don't have to edit a whole bunch of scripts every time a new repo is added.

But it does fix up the name table, which is a useful thing. I can add that as a one-liner with `gftools.utils.font_familyname`.

A source merge across hundreds of repos is a scarier prospect; it might allow for doing a VF build, which would be quite exciting. But not a priority. We trust fontTools.merge, don't we? ;-)

**Comment by davelab6** [comment]
> none of the scripts there [in nototools] are used in the current production process

I've therefore set the repo to Archive mode

**Comment by anthrotype** [comment]
I think the noto-emoji build toolchain for the bitmap CBDT color font still uses some of those nototools, perhaps we should wait before archiving it for good.

**Comment by davelab6** [comment]
@anthrotype the archive status in github is easily reversible, and won't effect usage, only pushing commits into the repo. Please ping me if you see that's needed :)

**Comment by anthrotype** [comment]
@davelab6 given that @rsheeter pushed some updates to some Unicode data files exposed via nototools API and used in noto color emoji toolchain as recently as 4 months ago for Unicode 15.1, I would say yes we do need to revert the archiving, at least until we find another place for those bits that are in fact still used.

**Comment by davelab6** [comment]
FYI It is un-archived :)
